### ISSUE TITLE
Which TensorFlow DLL?

### ISSUE THREAD

**Issue by Dingo64** [zsoltszakaly/tensorflowforpascal#6]
I tried both
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.11.0.zip
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-windows-x86_64-2.10.0.zip
and Lazarus complains:
`project1.lpr(1046,1) Error: Import library not found for tensorflow`

**Comment by zsoltszakaly** [comment]
I think the version you need depends on the hardware you have. You can compile your library according to your needs, but as I have a simple machine, I just use the plain vanilla CPU version. Even that could be accelerated as my CPU has some more feature not compiled in the downloadable binary, but I did not bother. For my library it does not matter which one you use, the external interface should be the same, only the internal calculations should work differently (optimized to the HW).

The error message is simply because lazarus cannot find the library itself. I am not too familiar with Windows (any more) but could you try in Project/Options/CompilerOptions/Path/Library path to set the location of your file? Don't you need to tell Windows it is a library. Or maybe in tf_api $linklib try name the file with the .dll extention. I am not sure. If you cannot solve it, let me know and will investigate further.

**Comment by Dingo64** [comment]
Thank you. It works with:
`{$linklib tensorflow.dll} `

**Comment by zsoltszakaly** [comment]
Good to hear. In the next update I will put in some code to check the environment and use the correct version.
